architect:
  - msuret
  - EtoileFilante
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  commanders:
    - msuret
    - EtoileFilante
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy --settings /home/r/settings.xml
    git checkout master
    git merge __rultor
docker:
  image: "teamed/docker-java-8"
